"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {chapterOne,groups,type Group,type Localized} from "../../../data/class8Science";
import styles from "./explorer.module.css";

type Lang="bn"|"en";
type Mode="explore"|"identify"|"challenge"|"remember";
const mysteries=["amphibia","arthropoda","aves","annelida","mollusca","reptilia","osteichthyes","mammalia","porifera","echinodermata"];
const choices=["amphibia","reptilia","aves","mammalia","annelida","arthropoda","mollusca","echinodermata"];

export default function AnimalExplorer(){
 const[lang,setLang]=useState<Lang>("bn");
 const[role,setRole]=useState<"teacher"|"student"|null>(null);
 const[mode,setMode]=useState<Mode>("explore");
 const[branch,setBranch]=useState<"invertebrate"|"vertebrate"|null>(null);
 const[selected,setSelected]=useState<Group|null>(null);
 const[index,setIndex]=useState(0);
 const[step,setStep]=useState(0);
 const[answer,setAnswer]=useState<string|null>(null);
 const[attempts,setAttempts]=useState(0);
 const[challenge,setChallenge]=useState(0);
 const[score,setScore]=useState(0);
 const[flipped,setFlipped]=useState<string|null>(null);
 const[showAnswer,setShowAnswer]=useState(false);
 useEffect(()=>{try{setLang(localStorage.getItem("bujhi-language")==="en"?"en":"bn")}catch{};void (async()=>{try{const r=await fetch("/api/me",{cache:"no-store"});if(!r.ok){location.replace("/login");return}const d=await r.json() as {profile?:{role?:string;class_level?:string}};if(d.profile?.role==="teacher")setRole("teacher");else if(d.profile?.role==="student"&&["8",8].includes(d.profile.class_level as string))setRole("student");else location.replace("/student-dashboard")}catch{location.replace("/login")}})()},[]);
 const t=(x:Localized)=>x[lang];
 const label=(bn:string,en:string)=>lang==="bn"?bn:en;
 const animal=useMemo(()=>groups.find(g=>g.id===mysteries[index])!,[index]);
 const current=useMemo(()=>groups.find(g=>g.id===choices[challenge%choices.length])!,[challenge]);
 const back=role==="teacher"?"/teacher-dashboard":"/student-dashboard/books/8/science/learn";
 function switchLang(){const next=lang==="bn"?"en":"bn";setLang(next);try{localStorage.setItem("bujhi-language",next)}catch{}}
 function nextAnimal(){setIndex((index+1)%mysteries.length);setStep(0);setAnswer(null);setAttempts(0)}
 const branches=[{key:"invertebrate" as const,title:{bn:"অমেরুদণ্ডী",en:"Invertebrates"},note:{bn:"মেরুদণ্ড নেই · ৮টি পর্ব",en:"No backbone · 8 phyla"}},{key:"vertebrate" as const,title:{bn:"মেরুদণ্ডী",en:"Vertebrates"},note:{bn:"কর্ডাটা পর্ব · ৭টি শ্রেণি",en:"Chordata · 7 classes"}}];
 if(!role)return <main className={styles.page}><p className={styles.loading}>{label("পাঠ খুলছে…","Opening lesson…")}</p></main>;
 return <main className={styles.page}>
  <header className={styles.header}><Link href={back} className={styles.back}>← {label("ডেস্কে ফিরি","Back to desk")}</Link><div className={styles.brand}><img src="/bujhi-icon.png" alt=""/> <strong>Bujhi</strong></div><button onClick={switchLang} className={styles.lang} aria-label="Change language">{lang==="bn"?"English":"বাংলা"}</button></header>
  <div className={styles.wrap}>
   <div className={styles.hero}><div><p>{label("অষ্টম শ্রেণি · বিজ্ঞান · ২০২৬ পাঠ্যবই · প্রথম অধ্যায়","Class 8 · Science · 2026 textbook · Chapter 1")}</p><h1>{t(chapterOne.title)}</h1><span>{label("দেখো → বৈশিষ্ট্য খুঁজে বের করো → কারণ বুঝে শ্রেণিবিন্যাস করো","Observe → find a feature → classify with a reason")}</span></div><a href="/nctb/2026/class-8/science-chapter-1.pdf" target="_blank" rel="noopener noreferrer" className={styles.book}>{label("মূল বই · পৃষ্ঠা ১–১২ ↗","Textbook · pages 1–12 ↗")}</a></div>
   {role==="teacher"&&<aside className={styles.teacher}><strong>{label("শিক্ষকের পাঠ পরিকল্পনা · ৪৫ মিনিট","Teacher guide · 45 minutes")}</strong><p>{label("৫ মিনিট পরিচিত প্রাণী দিয়ে শুরু → ১২ মিনিট শ্রেণিবিন্যাস বৃক্ষ → ১০ মিনিট বৈশিষ্ট্য ধরে শনাক্ত → ১০ মিনিট চ্যালেঞ্জ → ৮ মিনিট বইয়ের পৃষ্ঠা ১–১২ ও আলোচনা। প্রথমে শিক্ষার্থীদের অনুমান শুনুন, তারপর উদাহরণ দেখান।","5 min familiar animals → 12 min classification tree → 10 min identify by features → 10 min challenge → 8 min textbook pages 1–12 and discussion. Ask for a prediction before revealing the group.")}</p></aside>}
   <nav className={styles.tabs} aria-label="Learning modes">{(["explore","identify","challenge","remember"] as const).map((m,i)=><button key={m} onClick={()=>setMode(m)} className={mode===m?styles.active:""}>{i+1}. {label(["প্রাণিজগৎ ঘুরে দেখি","প্রাণী শনাক্ত করো","চ্যালেঞ্জ","মনে রাখি"][i],["Explore","Identify","Challenge","Remember"][i])}</button>)}</nav>
   {mode==="explore"&&<section className={styles.panel}><div className={styles.sectionHead}><div><small>{label("শ্রেণিবিন্যাসের মানচিত্র","Classification map")}</small><h2>{label("প্রাণীটি কোন শাখায়?","Which branch does it belong to?")}</h2></div><button className={styles.secondary} onClick={()=>{setBranch(null);setSelected(null)}}>{label("শুরুতে ফিরি","Reset tree")}</button></div><p>{label("প্রথমে মেরুদণ্ড আছে কি না দেখো। তারপর শাখা খুলে নির্দিষ্ট বৈশিষ্ট্য পড়ো।","First check for a backbone. Open a branch, then inspect a distinguishing feature.")}</p><div className={styles.tree}><div className={styles.root}>{label("প্রাণিজগৎ","Animal Kingdom")}</div><div className={styles.treeBranches}>{branches.map(b=><div key={b.key} className={styles.branch}><button className={branch===b.key?styles.branchActive:""} onClick={()=>{setBranch(branch===b.key?null:b.key);setSelected(null)}} aria-expanded={branch===b.key}><strong>{t(b.title)}</strong><small>{t(b.note)}</small></button>{branch===b.key&&<div className={styles.leaves}>{groups.filter(g=>g.branch===b.key).map(g=><button key={g.id} onClick={()=>setSelected(g)} className={selected?.id===g.id?styles.leafActive:""}>{t(g.name)}</button>)}</div>}</div>)}</div></div>{selected&&<article className={styles.detail} aria-live="polite"><small>{selected.branch==="vertebrate"?label("কর্ডাটা · শ্রেণি","Chordata · class"):label("অমেরুদণ্ডী · পর্ব","Invertebrate · phylum")}</small><h3>{t(selected.name)}</h3><p><b>{label("শনাক্ত করার বৈশিষ্ট্য:","Identifying feature:")}</b> {t(selected.feature)}</p><p><b>{label("উদাহরণ:","Example:")}</b> {t(selected.example)}</p></article>}</section>}
   {mode==="identify"&&<section className={styles.panel}><div className={styles.sectionHead}><div><small>{label("ধাপে ধাপে অনুসন্ধান","Step by step discovery")}</small><h2>{label("বৈশিষ্ট্য দেখে শনাক্ত করো","Identify from evidence")}</h2></div><span className={styles.counter}>{index+1}/{mysteries.length}</span></div><div className={styles.identify}><div className={styles.specimen}><span aria-hidden="true">🔎</span><h3>{t(animal.example)}</h3><p>{label("আগে অনুমান করো। প্রতিটি প্রশ্নের পর পরের সূত্র খুলবে।","Predict first. Each answer unlocks the next clue.")}</p><div className={styles.clue}>{step>0&&<p>1 · {animal.branch==="vertebrate"?label("মেরুদণ্ড আছে","Has a backbone"):label("মেরুদণ্ড নেই","No backbone")}</p>}{step>1&&<p>2 · {t(animal.feature)}</p>}</div></div><div className={styles.question}>{step===0?<><h3>{label("প্রথম প্রশ্ন: মেরুদণ্ড আছে?","First: does it have a backbone?")}</h3>{branches.map(b=><button key={b.key} onClick={()=>{if(b.key===animal.branch){setStep(1);setAnswer(null)}else setAnswer(b.key)}}>{t(b.title)}</button>)}{answer&&<p className={styles.feedback}>{label("আরও ভালো করে দেহের গঠন দেখো।","Look more closely at its body structure.")}</p>}</>:step===1?<><h3>{label("কোন বৈশিষ্ট্যটি সবচেয়ে উপযোগী?","Which feature best identifies it?")}</h3>{[animal,groups.find(g=>g.branch===animal.branch&&g.id!==animal.id)!].map(g=><button key={g.id} onClick={()=>{if(g.id===animal.id){setStep(2);setAnswer(null)}else setAnswer(g.id)}}>{t(g.feature)}</button>)}{answer&&<p className={styles.feedback}>{label("এটি অন্য একটি দলের বৈশিষ্ট্য। আবার দেখো।","That feature belongs to another group. Try again.")}</p>}</>:<><h3>{label("এবার দলটি বেছে নাও","Choose the group")}</h3>{[animal,...groups.filter(g=>g.branch===animal.branch&&g.id!==animal.id).slice(0,3)].sort((a,b)=>a.id.localeCompare(b.id)).map(g=><button key={g.id} onClick={()=>{setAnswer(g.id);setAttempts(attempts+1)}}>{t(g.name)}</button>)}{answer&&<p className={answer===animal.id?styles.success:styles.feedback}>{answer===animal.id?label(`${t(animal.example)}: ${t(animal.feature)}। তাই ${t(animal.name)}।`,`${t(animal.example)} has ${t(animal.feature).toLowerCase()}, so it belongs to ${t(animal.name)}.`):label(`এটি ${t(animal.name)}। বৈশিষ্ট্যটি মিলিয়ে আবার চেষ্টা করো।`,`Compare its feature again; this belongs to ${t(animal.name)}.`)}</p>}{answer===animal.id&&<button className={styles.primary} onClick={nextAnimal}>{label("পরের প্রাণী →","Next animal →")}</button>}</>}</div></div><small className={styles.attempts}>{label(`এবারের চেষ্টা: ${attempts}`,`Attempts this animal: ${attempts}`)}</small></section>}
   {mode==="challenge"&&<section className={styles.panel}><small>{label("বোঝা যাচাই","Retrieval check")}</small><h2>{label("বই বন্ধ করে চেষ্টা করো","Try without looking at the book")}</h2><p>{label("প্রাণীটির বৈশিষ্ট্য দেখে দল বেছে নাও। ভুল হলে কারণটি পড়ে আবার চেষ্টা করো।","Use the feature to choose a group. Read the explanation if you miss it.")}</p><div className={styles.challenge}><div><span>{challenge%choices.length+1}/{choices.length}</span><h3>{t(current.example)}</h3><p>{t(current.feature)}</p></div><div className={styles.choiceGrid}>{[current,...groups.filter(g=>g.branch===current.branch&&g.id!==current.id).slice(0,3)].sort((a,b)=>a.id.localeCompare(b.id)).map(g=><button disabled={showAnswer} key={g.id} onClick={()=>{setAnswer(g.id);setShowAnswer(true);if(g.id===current.id)setScore(score+1)}}>{t(g.name)}</button>)}</div></div>{showAnswer&&<div className={answer===current.id?styles.success:styles.feedback}>{answer===current.id?label("সঠিক!","Correct!"):label("আবার বৈশিষ্ট্যটি লক্ষ্য করো।","Look at the defining feature again.")} {t(current.example)} → {t(current.name)} · {t(current.feature)}<br/><button className={styles.primary} onClick={()=>{setChallenge(challenge+1);setAnswer(null);setShowAnswer(false)}}>{label("পরের প্রশ্ন →","Next question →")}</button></div>}<p className={styles.score}>{label(`সঠিক উত্তর: ${score} / ${challenge+(showAnswer?1:0)}`,`Correct: ${score} / ${challenge+(showAnswer?1:0)}`)}</p></section>}
   {mode==="remember"&&<section className={styles.panel}><small>{label("বইয়ের ভাষায় দেখি","Back to textbook terms")}</small><h2>{label("বৈশিষ্ট্য মনে রাখো, অনুচ্ছেদ নয়","Remember features, not paragraphs")}</h2><p>{label("কার্ডে চাপ দিয়ে উদাহরণ ও শনাক্তকারী বৈশিষ্ট্য দেখো।","Tap each card to reveal its example and identifying feature.")}</p><div className={styles.flashcards}>{groups.map(g=><button key={g.id} onClick={()=>setFlipped(flipped===g.id?null:g.id)} aria-expanded={flipped===g.id}><small>{g.branch==="vertebrate"?label("শ্রেণি","Class"):label("পর্ব","Phylum")}</small><strong>{t(g.name)}</strong><span>{flipped===g.id?`${t(g.example)} · ${t(g.feature)}`:label("দেখতে চাপ দাও","Tap to reveal")}</span></button>)}</div><a className={styles.book} href="/nctb/2026/class-8/science-chapter-1.pdf#page=3" target="_blank" rel="noopener noreferrer">{label("বইয়ের শ্রেণিবিন্যাসের চিত্র · মুদ্রিত পৃষ্ঠা ৩ ↗","Textbook classification chart · printed page 3 ↗")}</a></section>}
   <footer>{label("সূত্র: তোমার দেওয়া NCTB বিজ্ঞান, অষ্টম শ্রেণি, ২০২৬; অধ্যায় ১, মুদ্রিত পৃষ্ঠা ১–১২।","Source: your supplied NCTB Class 8 Science (2026), Chapter 1, printed pages 1–12.")}</footer>
  </div>
 </main>
}
