"use client";
import Link from "next/link";
import {useState} from "react";
import {ArrowLeft,ArrowRight,BookOpen,Lightbulb,MousePointer2,Sparkles} from "lucide-react";
const images=[{src:"/about-origin.png",label:"Where the question began",caption:"A familiar desk, a textbook, and the feeling that reading an answer was not the same as understanding it."},{src:"/about-classroom.png",label:"The classroom reality",caption:"Students do not all understand through the same explanation, at the same speed, or in the same form."},{src:"/about-practical.png",label:"The future we are building",caption:"Practical, visual and exploratory learning should begin long before a student reaches higher secondary school."}];
export default function About(){const[index,setIndex]=useState(0);return <main className="about-page"><header className="about-header"><Link className="brand" href="/"><img src="/bujhi-icon.png" alt=""/>Bujhi</Link><Link href="/"><ArrowLeft/>Back home</Link></header>
 <section className="about-hero"><div><p className="eyebrow">Our story</p><h1>Bujhi began with a frustration I knew personally.</h1><p>I learned how to prepare the expected answer. But preparing an answer and understanding an idea were not always the same thing.</p></div><button onClick={()=>document.getElementById("story")?.scrollIntoView({behavior:"smooth"})}><MousePointer2/>Follow the story</button></section>
 <section className="story-layout" id="story"><aside><span>01</span><p>A note from the founder</p></aside><article><h2>Knowing the words is not the same as knowing the idea.</h2><p>During my school years, I often studied by memorizing the exact language expected in examinations. When a difficult topic was explained once in only one way, students who could not connect with that explanation were easily made to feel that they were the problem.</p><p>I kept thinking about how late practical learning arrived. For many students in Bangladesh, a real science experiment, a working model, or even the freedom to explore a question can remain out of reach for years. No student should have to wait until Class 11 to properly touch laboratory equipment and see what a textbook concept actually means.</p><blockquote>“Sometimes the student does not need easier content. They need another path into the same concept.”</blockquote><p className="signature">Nusaiba Nusrat Zaman<br/><span>Founder, Bujhi · Dhaka, Bangladesh</span></p></article></section>
 <section className="story-gallery"><div className="gallery-frame"><img src={images[index].src} alt={images[index].label}/><span>{String(index+1).padStart(2,"0")} / 03</span></div><div><p className="eyebrow">Three views of the idea</p><h2>{images[index].label}</h2><p>{images[index].caption}</p><div className="gallery-tabs">{images.map((item,i)=><button className={index===i?"active":""} key={item.label} onClick={()=>setIndex(i)}>{String(i+1).padStart(2,"0")}</button>)}</div></div></section>
 <section className="fellowship"><Sparkles/><div><p className="eyebrow">Millennium Fellowship · SDG 4</p><h2>An idea gained a platform to become work.</h2><p>The Millennium Fellowship gave me the opportunity, structure and community to develop Bujhi as a social-impact project connected to Quality Education. It created space to research the problem, listen to students and teachers, test assumptions, and move from personal frustration toward a practical solution.</p></div></section>
 <section className="building"><p className="eyebrow">What we are trying to do</p><h2>One curriculum. More ways to understand and explain it.</h2><div><article><BookOpen/><h3>For students</h3><p>Read, watch, explore and practise the same topic until one approach finally makes sense.</p></article><article><Lightbulb/><h3>For teachers</h3><p>Find alternative explanations, classroom activities and practical ways to make difficult ideas visible.</p></article></div><Link href="/">Explore the homepage <ArrowRight/></Link></section>
 <footer className="site-footer"><Link className="brand" href="/"><img src="/bujhi-icon.png" alt=""/>Bujhi</Link><p>Built for understanding.</p><span>© 2026 Bujhi</span></footer>
 </main>}
