"use client";
import Link from "next/link";
import {useState} from "react";
import {ArrowRight,BookOpen,Check,ChevronLeft,ChevronRight,Compass,GraduationCap,LampDesk,Menu,MonitorPlay,PenLine,PlayCircle,Sparkles,X} from "lucide-react";
const subjects={Bangla:{icon:"ক",title:"Stories become worlds",copy:"Read literature closely, hear expression, explore context, then practise in your own words."},English:{icon:"A",title:"Language you can use",copy:"Build reading, writing and grammar through examples, audio and purposeful practice."},Mathematics:{icon:"π",title:"See how the answer works",copy:"Move from a visual idea to a worked example, then solve it yourself with helpful feedback."},Science:{icon:"⚗",title:"Investigate the everyday",copy:"Connect textbook concepts with experiments, simulations and the world around you."},"Social Studies":{icon:"◎",title:"Connect people and places",copy:"Explore history, geography and civics through stories, maps and real-life questions."}};
const modes=[{name:"Read",icon:BookOpen},{name:"Watch",icon:PlayCircle},{name:"Explore",icon:Compass},{name:"Practice",icon:PenLine}];
export default function Home(){const[subject,setSubject]=useState<keyof typeof subjects>("Science");const[mode,setMode]=useState("Read");const[page,setPage]=useState(1);const[lampOn,setLampOn]=useState(true);const[menuOpen,setMenuOpen]=useState(false);const current=subjects[subject];return <main>
<header className="nav-wrap"><nav className="nav"><Link href="/" className="brand"><img src="/bujhi-icon.png" alt=""/><span>Bujhi</span></Link><button className="menu-button" aria-label="Toggle navigation" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button><div className={`nav-links ${menuOpen?"open":""}`}><Link className="active" href="/">Home</Link><Link href="/about">About Us</Link><a href="#login">Login</a><a className="nav-signup" href="#join">Sign Up</a></div></nav></header>
<section className="hero"><div className="hero-grid"><div className="hero-copy"><p className="eyebrow">Built for the Bangladeshi curriculum</p><h1>Less memorizing.<br/>More understanding.</h1><p className="lead">One curriculum. Multiple ways to understand it.</p><p className="intro">Bujhi helps students approach every subject in the way that makes sense to them—and gives teachers more ways to make each idea click.</p><div className="hero-actions" id="join"><a className="button button-light" href="#login">Join as a Student <ArrowRight/></a><a className="button button-outline" href="#login">Join as a Teacher <ArrowRight/></a></div></div>
<div className={`desk ${lampOn?"lit":""}`}><button className="lamp" onClick={()=>setLampOn(!lampOn)} aria-pressed={lampOn}><LampDesk/><span>{lampOn?"Lamp on":"Lamp off"}</span></button><div className="paper paper-one"/><div className="paper paper-two"/><article className="notebook"><div className="spiral">{Array.from({length:9}).map((_,i)=><i key={i}/>)}</div><div className="notebook-topline"><span>Preview · Page {page} of 2</span><span className="preview-lock">Login to explore</span></div><h2>Every subject.<br/>Multiple ways to learn.</h2><div className="mode-tabs">{modes.map(({name,icon:Icon})=><button key={name} onClick={()=>setMode(name)} className={mode===name?"selected":""}><Icon/>{name}</button>)}</div>{page===1?<div className="lesson-preview"><div className="subject-mark">{current.icon}</div><div><p className="subject-name">{subject} · {mode}</p><h3>{current.title}</h3><p>{current.copy}</p></div></div>:<div className="approach-preview"><p className="subject-name">Four ways into one idea</p><div className="approach-grid">{modes.map(({name,icon:Icon})=><div key={name} className={mode===name?"focus":""}><Icon/><span>{name}</span></div>)}</div><p>Switch approaches whenever you need. Your progress stays connected to the same topic.</p></div>}<div className="page-controls"><button onClick={()=>setPage(1)} disabled={page===1}><ChevronLeft/></button><span>{page} / 2</span><button onClick={()=>setPage(2)} disabled={page===2}><ChevronRight/></button></div><div className="subject-tabs">{(Object.keys(subjects) as (keyof typeof subjects)[]).map(name=><button key={name} className={subject===name?"active":""} onClick={()=>{setSubject(name);setPage(1)}}>{name}</button>)}</div></article></div></div></section>
<div className="manifesto"><span>See it.</span><span>Question it.</span><span>Try it.</span><span>Understand it.</span></div>
<section className="offerings"><Offer type="student" number="01" kicker="For curious students" title="Find the explanation that finally clicks." text="Move beyond one-size-fits-all lessons with clear visuals, practical examples and activities that invite you to test ideas." items={["Visual explanations","Interactive exploration","Quizzes with useful feedback"]}/><Offer type="teacher" number="02" kicker="For inspiring teachers" title="Explain the same idea in more than one way." text="Plan engaging lessons with alternate explanations, classroom activities and ready-to-use curriculum resources." items={["Flexible teaching approaches","Classroom-ready activities","Curriculum-aligned resources"]}/></section>
<section className="story-strip"><div><Sparkles/><span>Why Bujhi began</span><h2>Learning should feel like understanding—not surviving the next exam.</h2></div><Link href="/about">Read our story <ArrowRight/></Link></section><section className="login-note" id="login"><p>Lessons, quizzes and teaching resources are available after you sign in.</p><button>Login access coming next</button></section><footer><Link href="/" className="brand"><img src="/bujhi-icon.png" alt=""/><span>Bujhi</span></Link><p>শুধু মুখস্থ নয়, বুঝে শিখি।</p><p>© 2026 Bujhi</p></footer></main>}
function Offer({type,number,kicker,title,text,items}:{type:string;number:string;kicker:string;title:string;text:string;items:string[]}){const Icon=type==="student"?GraduationCap:MonitorPlay;return <article className={`offering ${type}`}><div className="offering-art"><span>{number}</span><Icon/></div><div><p className="kicker">{kicker}</p><h2>{title}</h2><p>{text}</p><ul>{items.map(x=><li key={x}><Check/>{x}</li>)}</ul><a href="#login">Explore as a {type} <ArrowRight/></a></div></article>}
