"use client";
import Link from "next/link";
import {useState} from "react";
import {ArrowRight,BookOpen,Brain,Compass,FlaskConical,Menu,Pause,PenLine,Play,PlayCircle,Sparkles,X} from "lucide-react";

const modes={Read:{title:"A tiny universe on paper",copy:"Follow one clear idea at a time."},Watch:{title:"See motion make sense",copy:"Watch a difficult idea become visible."},Explore:{title:"The Solar System",copy:"Watch the planets orbit the Sun."},Practice:{title:"Try it without pressure",copy:"Choose, test, and learn from the answer."}};
const planetFacts=["Mercury finishes a year in only 88 Earth days.","Venus rotates in the opposite direction to most planets.","Earth is the only known world with liquid surface oceans.","Saturn would float in water if an ocean could hold it."];
const quickFacts=["A new explanation is not an easier lesson—it is another door into the same idea.","Writing what you understood in your own words is stronger than copying a definition.","Curiosity is a learning skill. It becomes better with practice."];

export default function Home(){
 const[menu,setMenu]=useState(false);const[mode,setMode]=useState<keyof typeof modes>("Explore");const[running,setRunning]=useState(true);const[planet,setPlanet]=useState(0);const[toast,setToast]=useState("");const[quiz,setQuiz]=useState(false);const[answer,setAnswer]=useState<number|null>(null);
 function note(text:string){setToast(text);window.setTimeout(()=>setToast(""),3200)}
 return <main>
  <header className="site-header"><nav><Link className="brand" href="/"><img src="/bujhi-icon.png" alt=""/>Bujhi</Link><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Open navigation">{menu?<X/>:<Menu/>}</button><div className={menu?"nav-links open":"nav-links"}><Link className="active" href="/">Home</Link><Link href="/about">About Us</Link><Link href="/login">Login</Link><Link className="sign-up" href="/register">Sign Up</Link></div></nav></header>
  <section className="hero">
   <div className="hero-copy"><p className="eyebrow">Built for the Bangladeshi curriculum</p><h1>Less memorizing.<br/>More understanding.</h1><p>One curriculum. Multiple ways to understand it.</p><div className="hero-actions"><Link href="/register?role=student">Join as a Student <ArrowRight/></Link><Link href="/register?role=teacher">Join as a Teacher <ArrowRight/></Link></div><button className="hidden-spark" onClick={()=>setQuiz(true)}><Sparkles/> I found something</button></div>
   <div className="notebook-wrap"><div className="paper back-one"/><div className="paper back-two"/><article className="notebook"><div className="rings">{Array.from({length:8}).map((_,i)=><i key={i}/>)}</div><div className="book-meta"><span>Interactive preview</span><span>Tap anything</span></div><h2>A peek inside Bujhi</h2><div className="mode-row">{Object.keys(modes).map(key=>{const Icon=key==="Read"?BookOpen:key==="Watch"?PlayCircle:key==="Explore"?Compass:PenLine;return <button key={key} className={mode===key?"active":""} onClick={()=>setMode(key as keyof typeof modes)}><Icon/>{key}</button>})}</div>
    <div className="lesson"><div className="lesson-copy"><p>{mode} · Universe</p><h3>{modes[mode].title}</h3><span>{modes[mode].copy}</span></div>{mode==="Explore"?<div className={running?"solar":"solar paused"}><button className="sun" onClick={()=>{setPlanet((planet+1)%planetFacts.length);note(planetFacts[(planet+1)%planetFacts.length])}} aria-label="Show a planet fact">☀</button>{[0,1,2,3].map(n=><button key={n} className={`orbit orbit-${n}`} onClick={()=>note(planetFacts[n])}><i/></button>)}</div>:<button className="mode-activity" onClick={()=>note(mode==="Read"?"Try reading the idea aloud, then explain it without looking.":mode==="Watch"?"Imagine a time-lapse showing one full orbit.":"Quick check: Earth takes about 365 days to orbit the Sun.")}>{mode==="Read"?<BookOpen/>:mode==="Watch"?<Play/>:<Brain/>}<span>Try this approach</span></button>}</div>
    <footer className="book-footer"><button onClick={()=>setRunning(!running)}>{running?<Pause/>:<Play/>}{running?"Pause orbit":"Play orbit"}</button><span>Tap a planet for a fact</span></footer>
   </article></div>
  </section>
  <section className="touch-strip"><button onClick={()=>note(quickFacts[0])}><BookOpen/><span>Open a thought</span></button><button onClick={()=>setQuiz(true)}><Brain/><span>Try a hidden quiz</span></button><button onClick={()=>note(quickFacts[Math.floor(Math.random()*quickFacts.length)])}><Sparkles/><span>Find a tiny fact</span></button><button onClick={()=>note("Look around you: what textbook idea can you find in the room?")}><FlaskConical/><span>Start an experiment</span></button></section>
  <section className="promise"><p className="eyebrow">One idea, more than one path</p><h2>When one explanation does not click, try another.</h2><div><article><b>01</b><h3>See it</h3><p>Visual explanations reveal what words can hide.</p></article><article><b>02</b><h3>Connect it</h3><p>Everyday examples make ideas feel real.</p></article><article><b>03</b><h3>Try it</h3><p>Small activities turn information into understanding.</p></article></div><Link href="/about">Why Bujhi exists <ArrowRight/></Link></section>
  <footer className="site-footer"><Link className="brand" href="/"><img src="/bujhi-icon.png" alt=""/>Bujhi</Link><p>শুধু মুখস্থ নয়, বুঝে শিখি।</p><span>© 2026 Bujhi</span></footer>
  {quiz&&<div className="modal" onMouseDown={e=>{if(e.target===e.currentTarget){setQuiz(false);setAnswer(null)}}}><section><button className="close" onClick={()=>{setQuiz(false);setAnswer(null)}}><X/></button><p className="eyebrow">Hidden desk quiz</p><h2>Why do we experience seasons?</h2>{["Earth moves closer to the Sun","Earth’s axis is tilted","The Sun becomes colder"].map((item,i)=><button className={`quiz-option ${answer===i?(i===1?"correct":"wrong"):""}`} key={item} onClick={()=>setAnswer(i)}>{item}</button>)}{answer!==null&&<p className="result">{answer===1?"Exactly. The tilt changes how directly sunlight reaches each hemisphere.":"Not quite. Distance is not the main reason—try the tilt."}</p>}</section></div>}
  {toast&&<div className="toast">{toast}</div>}
 </main>
}
