"use client";

import Link from "next/link";
import {useParams} from "next/navigation";
import {useEffect,useState} from "react";
import styles from "./lesson.module.css";

type Lang="bn"|"en";
type Pair=[string,string];
const chapters={
 "chapter-3":{number:3,title:["ব্যাপন, অভিস্রবণ ও প্রস্বেদন","Diffusion, Osmosis and Transpiration"] as Pair,pages:[29,38],hook:["পানিতে কালি মেশালে কী ঘটে? গাছের পাতায় পলিথিন বেঁধে রাখলে পানি আসে কোথা থেকে?","What happens when ink enters water? Where do droplets in a bag around a leaf come from?"],teacher:["পানিতে রঙ ছড়িয়ে পড়ার প্রদর্শন → ব্যাপন মডেল → অর্ধভেদ্য পর্দার পরীক্ষা → পাতায় পলিথিন বেঁধে পর্যবেক্ষণ → মূল থেকে পাতায় পানি পরিবহন।","Demonstrate dye spreading → particle model → semipermeable membrane experiment → bag on leaves → trace water from roots to leaves."],topics:[["ব্যাপন","Diffusion"],["অভিস্রবণ","Osmosis"],["প্রস্বেদন ও পানি পরিবহন","Transpiration and transport"]] as Pair[]},
 "chapter-4":{number:4,title:["উদ্ভিদের বংশ বৃদ্ধি","Plant Reproduction"] as Pair,pages:[39,49],hook:["আলু থেকে নতুন গাছ হয়, আবার ফুলের বীজ থেকেও গাছ হয়। দুটি পথ কীভাবে আলাদা?","A potato can form a new plant, and so can a seed. How are the two routes different?"],teacher:["আলু/আদা ও একটি প্রকৃত ফুল দেখান → অংশ শনাক্ত → পরাগায়নের পথ অনুসরণ → ভেজানো বীজের গঠন ও অঙ্কুরোদ্গম পর্যবেক্ষণ।","Show potato/ginger and a real flower → label parts → trace pollination → observe a soaked seed and germination."],topics:[["অঙ্গজ জনন","Vegetative reproduction"],["ফুল ও পরাগায়ন","Flower and pollination"],["নিষেক ও ফল গঠন","Fertilization and fruit"],["বীজ ও অঙ্কুরোদ্গম","Seed and germination"]] as Pair[]},
 "chapter-5":{number:5,title:["সমন্বয় ও নিঃসরণ","Coordination and Excretion"] as Pair,pages:[50,59],hook:["গরম কিছু ছুঁলে হাত সঙ্গে সঙ্গে সরে যায় কেন? জানালার দিকে গাছ কেন বাড়ে?","Why does your hand pull away from heat? Why does a plant grow toward a window?"],teacher:["আলোর দিকে গাছের বৃদ্ধি নিয়ে পূর্বানুমান → স্নায়ু ও প্রতিবর্ত পথ সাজানো → মস্তিষ্ক/সুষুম্নাকাণ্ডের ভূমিকা → বৃক্কের নিঃসরণ পথ।","Predict plant response to light → assemble a reflex arc → discuss brain/spinal cord → follow the kidney excretion route."],topics:[["উদ্ভিদের সমন্বয়","Plant coordination"],["প্রতিবর্ত ক্রিয়া","Reflex action"],["মস্তিষ্ক ও স্নায়ু","Brain and nerves"],["নিঃসরণ","Excretion"]] as Pair[]},
 "chapter-6":{number:6,title:["পরমাণুর গঠন","Structure of the Atom"] as Pair,pages:[60,69],hook:["অক্সিজেনের ৮টি প্রোটন থাকলে তার পারমাণবিক সংখ্যা কত? নিউট্রন বদলালে মৌলটি বদলায়?","If oxygen has 8 protons, what is its atomic number? Does changing neutrons change the element?"],teacher:["প্রোটন/নিউট্রন/ইলেকট্রন দিয়ে পরমাণু সাজান → পারমাণবিক ও ভরসংখ্যা গণনা → আইসোটোপ তুলনা → ইলেকট্রন খোলকে বসানো।","Build an atom with protons/neutrons/electrons → calculate atomic and mass numbers → compare isotopes → arrange electrons in shells."],topics:[["পরমাণু তৈরি","Build an atom"],["আইসোটোপ","Isotopes"],["ইলেকট্রন বিন্যাস","Electron arrangement"]] as Pair[]}
} as const;
const waterPath:Pair[]=[["মাটি","Soil"],["মূলরোম","Root hair"],["জাইলেম","Xylem"],["পাতা","Leaf"],["পত্ররন্ধ্র","Stomata"],["বায়ুমণ্ডল","Air"]];
const reflexPath:Pair[]=[["উদ্দীপনা","Stimulus"],["গ্রাহক","Receptor"],["সংবেদী স্নায়ু","Sensory neuron"],["সুষুম্নাকাণ্ড","Spinal cord"],["চালক স্নায়ু","Motor neuron"],["পেশি","Muscle"],["হাত সরানো","Withdrawal"]];
const excretionPath:Pair[]=[["রক্ত","Blood"],["বৃক্ক","Kidney"],["মূত্রনালি","Ureter"],["মূত্রথলি","Bladder"],["মূত্রনিষ্কাশন","Urination"]];
const plantParts:Pair[]=[["পরাগধানী","Anther"],["পরাগদণ্ড","Filament"],["গর্ভমুণ্ড","Stigma"],["গর্ভদণ্ড","Style"],["ডিম্বাশয়","Ovary"],["ডিম্বক","Ovule"]];
const vegetative=[{plant:["আলু","Potato"] as Pair,part:["কাণ্ডের কন্দ","Stem tuber"] as Pair},{plant:["আদা","Ginger"] as Pair,part:["ভূগর্ভস্থ কাণ্ড","Underground stem"] as Pair},{plant:["পেঁয়াজ","Onion"] as Pair,part:["বাল্ব","Bulb"] as Pair},{plant:["পাথরকুচি","Bryophyllum"] as Pair,part:["পাতা","Leaf"] as Pair}];
function clamp(n:number,min:number,max:number){return Math.min(max,Math.max(min,n))}

export default function ScienceLesson(){
 const params=useParams();const slug=String(params.chapter||"");const chapter=chapters[slug as keyof typeof chapters];
 const[lang,setLang]=useState<Lang>("bn"),[role,setRole]=useState<"student"|"teacher"|null>(null);
 const[topic,setTopic]=useState(0),[prediction,setPrediction]=useState<string|null>(null),[observed,setObserved]=useState(false),[explanation,setExplanation]=useState("");
 const[temperature,setTemperature]=useState(24),[concentration,setConcentration]=useState(7),[elapsed,setElapsed]=useState(0),[running,setRunning]=useState(false);
 const[flow,setFlow]=useState(0),[flowerPart,setFlowerPart]=useState(0),[lightSide,setLightSide]=useState<"left"|"right">("left");
 const[quizAnswers,setQuizAnswers]=useState<Record<number,number>>({}),[protons,setProtons]=useState(8),[neutrons,setNeutrons]=useState(8),[electrons,setElectrons]=useState(8);
 useEffect(()=>{try{setLang(localStorage.getItem("bujhi-language")==="en"?"en":"bn")}catch{};void(async()=>{try{const r=await fetch("/api/me",{cache:"no-store"});if(!r.ok){location.replace("/login");return}const data=await r.json() as {profile?:{role?:string;class_level?:string}};if(data.profile?.role==="teacher")setRole("teacher");else if(data.profile?.role==="student"&&String(data.profile.class_level)==="8")setRole("student");else location.replace("/student-dashboard")}catch{location.replace("/login")}})()},[]);
 useEffect(()=>{if(!running)return;const timer=window.setInterval(()=>setElapsed(v=>Math.min(100,v+Math.max(1,Math.round((temperature/20)*(concentration/5))))),450);return()=>window.clearInterval(timer)},[running,temperature,concentration]);
 const t=(pair:Pair|readonly [string,string])=>pair[lang==="bn"?0:1];const l=(bn:string,en:string)=>lang==="bn"?bn:en;
 const back=role==="teacher"?"/teacher-dashboard":"/student-dashboard/books/8/science/learn";
 if(!chapter)return <main className={styles.page}><Link href="/student-dashboard/books/8/science/learn">Chapter not found · Back to Science</Link></main>;
 if(!role)return <main className={styles.page}><p className={styles.loading}>{l("পাঠ খুলছে…","Opening lesson…")}</p></main>;
 const phase=(items:Pair[])=> <div className={styles.flow} aria-label={l("ধাপে ধাপে পথ","Step by step pathway")}>{items.map((item,i)=><button key={i} className={i===flow?styles.current:""} onClick={()=>setFlow(i)}>{i+1}. {t(item)}</button>)}</div>;
 const nextFlow=(length:number)=><div className={styles.controls}><button onClick={()=>setFlow(Math.max(0,flow-1))} disabled={flow===0}>← {l("আগে","Previous")}</button><button onClick={()=>setFlow(Math.min(length-1,flow+1))} disabled={flow===length-1}>{l("পরে","Next")} →</button></div>;
 function chooseTopic(i:number){setTopic(i);setPrediction(null);setObserved(false);setExplanation("");setFlow(0)}
 const shellCounts=[Math.min(electrons,2),Math.min(Math.max(electrons-2,0),8),Math.min(Math.max(electrons-10,0),8)];
 return <main className={styles.page}><header className={styles.top}><Link href={back}>← {l("বইয়ের পাঠে ফিরি","Back to lessons")}</Link><strong><img src="/bujhi-icon.png" alt=""/> Bujhi</strong><button onClick={()=>{const next=lang==="bn"?"en":"bn";setLang(next);try{localStorage.setItem("bujhi-language",next)}catch{}}}>{lang==="bn"?"English":"বাংলা"}</button></header>
 <div className={styles.wrap}><section className={styles.hero}><div><small>{l(`অষ্টম শ্রেণি · বিজ্ঞান · ২০২৬ · অধ্যায় ${chapter.number}`,`Class 8 · Science · 2026 · Chapter ${chapter.number}`)}</small><h1>{t(chapter.title)}</h1><p>{t(chapter.hook)}</p></div><a href={`/nctb/2026/class-8/science.pdf#page=${chapter.pages[0]}`} target="_blank" rel="noopener noreferrer">{l(`মূল বই · পৃষ্ঠা ${chapter.pages[0]-5}–${chapter.pages[1]-5} ↗`,`Textbook · pages ${chapter.pages[0]-5}–${chapter.pages[1]-5} ↗`)}</a></section>
 {role==="teacher"&&<aside className={styles.teacher}><strong>{l("শিক্ষকের ৪৫ মিনিটের পাঠক্রম","Teacher's 45 minute sequence")}</strong><p>{t(chapter.teacher)}</p><small>{l("দেখানোর আগে শিক্ষার্থীর পূর্বানুমান শুনুন। ব্যবহারিক কাজের ফলের সঙ্গে মডেলটি মিলিয়ে দেখান।","Ask for a prediction before showing the model; compare it with the practical observation.")}</small></aside>}
 <nav className={styles.tabs} aria-label="Topics">{chapter.topics.map((item,i)=><button className={i===topic?styles.active:""} key={i} onClick={()=>chooseTopic(i)}>{i+1}. {t(item)}</button>)}</nav>
 <section className={styles.panel}><small>{l("অনুমান → পর্যবেক্ষণ → ব্যাখ্যা","Predict → Observe → Explain")}</small><h2>{t(chapter.topics[topic])}</h2>
 <div className={styles.predict}><strong>{l("শুরুতে কী ঘটবে বলে মনে হয়?","What do you predict will happen?")}</strong><div><button className={prediction==="a"?styles.chosen:""} onClick={()=>setPrediction("a")}>{l("পরিবর্তন দেখা যাবে","I expect a change")}</button><button className={prediction==="b"?styles.chosen:""} onClick={()=>setPrediction("b")}>{l("কোনো পরিবর্তন হবে না","I expect no change")}</button></div></div>
 {chapter.number===3&&topic===0&&<div className={styles.sim}><h3>{l("পানিতে রঙের কণা ছড়িয়ে পড়া","Dye particles spreading in water")}</h3><p>{l("প্রথমে আসল পানিতে খাবার রং ফেলে দেখো। তারপর এই মডেলে তাপমাত্রা ও শুরুর ঘনত্ব বদলে তুলনা করো।","First drop food colour into real water. Then watch this conceptual model and change temperature and starting concentration.")}</p><div className={styles.tank}>{Array.from({length:30},(_,i)=><span key={i} className={styles.particle} style={{left:`${10+(i%5)*2+((i*37)%72)*elapsed/100}%`,top:`${18+(i%7)*8+((i*19)%18)*elapsed/100}%`,opacity:i<concentration*3?.9:.25}}/>)}</div><div className={styles.sliders}><label>{l("তাপমাত্রা","Temperature")} {temperature}°C<input type="range" min="10" max="50" value={temperature} onChange={e=>setTemperature(+e.target.value)}/></label><label>{l("শুরুর ঘনত্ব","Starting concentration")} {concentration}<input type="range" min="2" max="10" value={concentration} onChange={e=>setConcentration(+e.target.value)}/></label></div><div className={styles.controls}><button onClick={()=>{setElapsed(0);setRunning(false)}}>{l("আবার শুরু","Reset")}</button><button onClick={()=>{setRunning(!running);setObserved(true)}}>{running?l("থামাও","Pause"):l("চালাও","Play")}</button><span>{l("বিস্তারের ধাপ","Spread")}: {elapsed}%</span></div><p className={styles.fact}>{l("এটি কণার গতির ধারণামূলক মডেল; সঠিক গতি বা দূরত্বের পরিমাপ নয়।","This is a conceptual particle model, not a measured speed or distance.")}</p></div>}
 {chapter.number===3&&topic===1&&<div className={styles.sim}><h3>{l("অর্ধভেদ্য পর্দা দিয়ে পানির চলাচল","Water crossing a semipermeable membrane")}</h3><div className={styles.membrane}><div><b>{l("পাতলা দ্রবণ","Dilute solution")}</b><span>H₂O H₂O H₂O H₂O</span></div><div className={styles.divider}>╎╎╎ →</div><div><b>{l("ঘন দ্রবণ","Concentrated solution")}</b><span>H₂O + ● ● ●</span></div></div><button onClick={()=>{setObserved(true);setFlow((flow+1)%3)}}>{l("পানির পথ দেখাও","Trace water")}</button><p>{flow===0?l("পানি বেশি আছে কোন পাশে?","Which side has more available water?"):flow===1?l("পানি অর্ধভেদ্য পর্দা পার হয়ে ঘন দ্রবণের দিকে যায়।","Water crosses the semipermeable membrane toward the more concentrated solution."):l("দ্রবের কণাগুলো পর্দা পার হচ্ছে না—পানি চলেছে।","The solute particles do not cross here; water does.")}</p><p className={styles.fact}>{l("বইয়ের অভিস্রবণের পরীক্ষার সঙ্গে মিলিয়ে দেখো।","Compare with the osmosis experiment in the textbook.")}</p></div>}
 {chapter.number===3&&topic===2&&<div className={styles.sim}><h3>{l("মাটি থেকে বাতাসে পানির পথ","Water's route from soil to air")}</h3>{phase(waterPath)}{nextFlow(waterPath.length)}<p className={styles.focus}>{l("এখন: ","Now: ")}{t(waterPath[flow])}</p><button onClick={()=>setObserved(true)}>{l("পাতায় পলিথিন বেঁধে পরীক্ষার ফল দেখো","Reveal bag-on-leaf observation")}</button>{observed&&<p className={styles.fact}>{l("কিছুক্ষণ পরে ব্যাগের ভেতরে ফোঁটা জমে। পাতার পত্ররন্ধ্র দিয়ে বের হওয়া জলীয় বাষ্প ঠান্ডা হয়ে ফোঁটা হয়।","Droplets collect inside the bag as water vapour from the leaves condenses.")}</p>}</div>}
 {chapter.number===4&&topic===0&&<div className={styles.sim}><h3>{l("গাছের কোন অংশ থেকে নতুন গাছ?","Which part forms a new plant?")}</h3><div className={styles.cards}>{vegetative.map((v,i)=><button key={i} onClick={()=>{setFlowerPart(i);setObserved(true)}} className={flowerPart===i?styles.selectedCard:""}>{t(v.plant)}</button>)}</div>{observed&&<p className={styles.focus}>{t(vegetative[flowerPart].plant)} → {t(vegetative[flowerPart].part)} · {l("অঙ্গজ জনন","vegetative reproduction")}</p>}<p>{l("বাড়িতে/শ্রেণিকক্ষে আসল নমুনা দেখে অংশটি শনাক্ত করো।","Inspect a real specimen at home or in class to identify the part.")}</p></div>}
 {chapter.number===4&&topic===1&&<div className={styles.sim}><h3>{l("ফুলের অংশে চাপ দাও","Tap a flower part")}</h3><div className={styles.flower}><div aria-hidden="true">✿</div><div className={styles.cards}>{plantParts.map((part,i)=><button key={i} className={flowerPart===i?styles.selectedCard:""} onClick={()=>{setFlowerPart(i);setObserved(true)}}>{t(part)}</button>)}</div></div><p className={styles.focus}>{l("নির্বাচিত অংশ:","Selected part:")} {t(plantParts[flowerPart])}</p><div className={styles.flow}><button onClick={()=>{setFlow(0);setObserved(true)}} className={flow===0?styles.current:""}>{l("একই ফুলে পরাগায়ন","Self pollination")}</button><button onClick={()=>{setFlow(1);setObserved(true)}} className={flow===1?styles.current:""}>{l("ভিন্ন গাছে পরাগায়ন","Cross pollination")}</button></div><p>{flow===0?l("একই ফুল বা একই গাছের অন্য ফুলের পরাগ গর্ভমুণ্ডে পৌঁছায়।","Pollen reaches a stigma on the same flower or another flower of the same plant."):l("একই প্রজাতির অন্য গাছের ফুলে পরাগ পৌঁছায়।","Pollen reaches a flower on another plant of the same species.")}</p><p className={styles.fact}>{l("পরাগধানী → গর্ভমুণ্ড; পরাগায়ন ও নিষেক এক ঘটনা নয়।","Anther → stigma; pollination and fertilization are different events.")}</p></div>}
 {chapter.number===4&&topic===3&&<div className={styles.sim}><h3>{l("বীজ থেকে নতুন গাছ","From seed to seedling")}</h3>{phase([["বীজ ভেজানো","Soak seed"],["বীজত্বক ফেটে যায়","Seed coat splits"],["ভ্রূণমূল বের হয়","Root emerges"],["কাণ্ড ও পাতা বের হয়","Shoot and leaves grow"]])}{nextFlow(4)}<p className={styles.focus}>{l("আসল মুগ/ছোলার বীজ ভিজিয়ে কয়েক দিন পর্যবেক্ষণ করো।","Soak a real bean or gram seed and observe it over several days.")}</p></div>}
 {chapter.number===4&&topic===2&&<div className={styles.sim}><h3>{l("পরাগ থেকে ফল পর্যন্ত","From pollen to fruit")}</h3>{phase([["পরাগ গর্ভমুণ্ডে পড়ে","Pollen lands on stigma"],["পরাগনালি গর্ভদণ্ডের ভেতর বাড়ে","Pollen tube grows through style"],["ডিম্বকে নিষেক ঘটে","Fertilization occurs at ovule"],["ডিম্বক বীজ, ডিম্বাশয় ফল হয়","Ovule becomes seed; ovary becomes fruit"]])}{nextFlow(4)}<p className={styles.fact}>{l("পরাগায়ন হলো পরাগ পৌঁছানো; নিষেক হলো জননকোষের মিলন।","Pollination is pollen transfer; fertilization is the joining of reproductive cells.")}</p></div>}
 {chapter.number===5&&topic===0&&<div className={styles.sim}><h3>{l("গাছ কোন দিকে বাড়বে?","Which way will the shoot grow?")}</h3><div className={styles.plant}><span className={lightSide==="left"?styles.sunLeft:styles.sunRight}>☀</span><svg viewBox="0 0 260 170" role="img" aria-label={l("আলোর দিকে বাঁকানো গাছের ধারণামূলক চিত্র","Diagram of a shoot bending toward light")}><path d={lightSide==="left"?"M130 160 Q132 92 74 40":"M130 160 Q128 92 186 40"} stroke="#47744a" strokeWidth="10" fill="none" strokeLinecap="round"/><ellipse cx="130" cy="160" rx="35" ry="8" fill="#94775d"/></svg></div><div className={styles.controls}><button onClick={()=>{setLightSide("left");setObserved(true)}}>{l("বামে আলো","Light left")}</button><button onClick={()=>{setLightSide("right");setObserved(true)}}>{l("ডানে আলো","Light right")}</button></div><p>{l("কয়েক দিন জানালার পাশে রাখা গাছের বৃদ্ধির দিক পরীক্ষা করো।","Observe a plant by a window for several days and compare its growth direction.")}</p></div>}
 {chapter.number===5&&topic===1&&<div className={styles.sim}><h3>{l("গরম বস্তু থেকে হাত সরানোর প্রতিবর্ত পথ","Reflex arc: pulling away from heat")}</h3>{phase(reflexPath)}{nextFlow(reflexPath.length)}<p className={styles.focus}>{t(reflexPath[flow])}</p><p className={styles.fact}>{l("দ্রুত প্রতিবর্ত ক্রিয়ায় সুষুম্নাকাণ্ড গুরুত্বপূর্ণ। এটি ইচ্ছাকৃত সিদ্ধান্তের জন্য অপেক্ষা করে না।","The spinal cord coordinates this rapid reflex without waiting for a deliberate decision.")}</p></div>}
 {chapter.number===5&&topic===3&&<div className={styles.sim}><h3>{l("বৃক্ক থেকে মূত্র বের হওয়ার পথ","Path of urine through the excretory system")}</h3>{phase(excretionPath)}{nextFlow(excretionPath.length)}<p className={styles.focus}>{t(excretionPath[flow])}</p><p>{l("বৃক্ক রক্ত থেকে বর্জ্য অপসারণ করে। এই চিত্রে কেবল প্রধান পথ দেখানো হয়েছে।","Kidneys remove wastes from blood. This diagram shows the main route only.")}</p></div>}
 {chapter.number===5&&topic===2&&<div className={styles.sim}><h3>{l("স্নায়ুতন্ত্রের প্রধান অংশ","Main parts of the nervous system")}</h3>{phase([["মস্তিষ্ক: তথ্য সমন্বয়","Brain: integrates information"],["সুষুম্নাকাণ্ড: মস্তিষ্কের সঙ্গে যোগাযোগ ও প্রতিবর্ত","Spinal cord: connects brain and mediates reflexes"],["স্নায়ু: দেহজুড়ে সংকেত বহন","Nerves: carry signals through the body"]])}{nextFlow(3)}<p className={styles.focus}>{t(([["মস্তিষ্ক: তথ্য সমন্বয়","Brain: integrates information"],["সুষুম্নাকাণ্ড: মস্তিষ্কের সঙ্গে যোগাযোগ ও প্রতিবর্ত","Spinal cord: connects brain and mediates reflexes"],["স্নায়ু: দেহজুড়ে সংকেত বহন","Nerves: carry signals through the body"]] as Pair[])[flow])}</p></div>}
 {chapter.number===6&&<div className={styles.sim}><h3>{l("নিজের পরমাণু তৈরি করো","Build your atom")}</h3><div className={styles.atom}><div className={styles.orbit}><div className={styles.nucleus}>p⁺ {protons}<br/>n⁰ {neutrons}</div><span>e⁻ {electrons}</span></div><div className={styles.sliders}>{([["প্রোটন","Protons",protons,setProtons],["নিউট্রন","Neutrons",neutrons,setNeutrons],["ইলেকট্রন","Electrons",electrons,setElectrons]] as const).map(([bn,en,value,setter])=><label key={bn}>{l(bn,en)} <strong>{value}</strong><input type="range" min="1" max="18" value={value} onChange={e=>{setter(clamp(+e.target.value,1,18));setObserved(true)}}/></label>)}</div></div><div className={styles.metrics}><span>{l("পারমাণবিক সংখ্যা","Atomic number")} <b>{protons}</b></span><span>{l("ভরসংখ্যা","Mass number")} <b>{protons+neutrons}</b></span><span>{l("আধান","Charge")} <b>{protons-electrons}</b></span></div>{topic===0&&<p>{l("প্রোটন বদলালে মৌল বদলায়। নিরপেক্ষ পরমাণুতে প্রোটন ও ইলেকট্রন সংখ্যা সমান।","Changing protons changes the element. A neutral atom has equal protons and electrons.")}</p>}{topic===1&&<div className={styles.fact}>{l(`এই পরমাণু: ${protons} প্রোটন + ${neutrons} নিউট্রন। শুধু নিউট্রন বদলাও—পারমাণবিক সংখ্যা একই, ভরসংখ্যা বদলায়।`,`This atom: ${protons} protons + ${neutrons} neutrons. Change only neutrons: atomic number stays the same while mass number changes.`)}</div>}{topic===2&&<div className={styles.fact}>{l("প্রথম তিন খোলকে ইলেকট্রন (এই পাঠে প্রথম ১৮টির মডেল): ","Electrons in the first three shells (model for the first 18): ")}{shellCounts.join(" · ")}. {l("Na-এর জন্য ১১ ইলেকট্রন দিয়ে দেখো: ২ · ৮ · ১।","Try 11 electrons for Na: 2 · 8 · 1.")}</div>}<small>{l("মডেলটি ধারণামূলক; ইলেকট্রনের প্রকৃত অবস্থান বা কক্ষপথের স্কেল নয়।","Conceptual model; not the physical scale or actual electron orbit.")}</small></div>}
 <div className={styles.check}><h3>{l("বই বন্ধ করে বোঝা যাচাই","Check understanding without the book")}</h3>{([
   {q:["ব্যাপনে কণা সাধারণত কোন দিকে ছড়ায়?","In diffusion, which direction is the net spread?"],a:[["বেশি ঘনত্ব থেকে কম ঘনত্বে","Higher to lower concentration"],["কম থেকে বেশি ঘনত্বে","Lower to higher concentration"]],correct:0},
   {q:["অভিস্রবণে অর্ধভেদ্য পর্দা দিয়ে কোনটি চলে?","What moves across the semipermeable membrane in osmosis?"],a:[["পানি","Water"],["সব দ্রব কণা","All solute particles"]],correct:0},
   {q:["অঙ্গজ জননে বীজ আবশ্যক?","Does vegetative reproduction require a seed?"],a:[["না","No"],["হ্যাঁ","Yes"]],correct:0},
   {q:["ফুলের কোন অংশ ফল হয়?","Which flower part becomes fruit?"],a:[["ডিম্বাশয়","Ovary"],["পরাগধানী","Anther"]],correct:0},
   {q:["দ্রুত প্রতিবর্ত ক্রিয়ায় কোন অংশটি প্রধান ভূমিকা রাখে?","What plays a key role in a rapid reflex?"],a:[["সুষুম্নাকাণ্ড","Spinal cord"],["বৃক্ক","Kidney"]],correct:0},
   {q:["বৃক্কের প্রধান কাজ কী?","What is a main job of the kidneys?"],a:[["রক্ত থেকে বর্জ্য অপসারণ","Remove wastes from blood"],["স্নায়ু সংকেত পাঠানো","Send nerve signals"]],correct:0},
   {q:["পারমাণবিক সংখ্যা নির্ধারণ করে কী?","What determines atomic number?"],a:[["প্রোটন সংখ্যা","Number of protons"],["নিউট্রন সংখ্যা","Number of neutrons"]],correct:0},
   {q:["আইসোটোপে একই থাকে কী?","What stays the same in isotopes of an element?"],a:[["প্রোটন সংখ্যা","Number of protons"],["নিউট্রন সংখ্যা","Number of neutrons"]],correct:0}
  ] as const).slice((chapter.number-3)*2,(chapter.number-2)*2).map((item,i)=><div key={i} className={styles.question}><strong>{i+1}. {t(item.q)}</strong><div>{item.a.map((choice,j)=><button key={j} onClick={()=>setQuizAnswers({...quizAnswers,[i]:j})} className={quizAnswers[i]===j?styles.chosen:""}>{t(choice)}</button>)}</div>{quizAnswers[i]!==undefined&&<small>{quizAnswers[i]===item.correct?l("সঠিক। কারণটি নিজের ভাষায় বলো।","Correct. Explain why in your own words."):l("আবার পাঠের মডেলটি দেখে চেষ্টা করো।","Review the model and try again.")}</small>}</div>)}</div>
 <div className={styles.explain}><strong>{l("নিজের ভাষায় কারণ লিখো","Explain in your own words")}</strong><textarea value={explanation} onChange={e=>setExplanation(e.target.value)} placeholder={l("পর্যবেক্ষণটি কেন হলো?","Why did you observe this?")} maxLength={600}/><small>{l("এই নোট শুধু তোমার ডিভাইসে এই সেশনে থাকে।","This note stays in this browser session.")}</small></div>
 <div className={styles.connect}><strong>{l("এখন বইয়ের ভাষায় দেখি","Back to textbook language")}</strong><p>{l(`অধ্যায় ${chapter.number} · মুদ্রিত পৃষ্ঠা ${chapter.pages[0]-5}–${chapter.pages[1]-5}। পর্যবেক্ষণের সঙ্গে বইয়ের চিত্র ও সংজ্ঞা মিলিয়ে দেখো।`,`Chapter ${chapter.number} · printed pages ${chapter.pages[0]-5}–${chapter.pages[1]-5}. Compare the observation with the book's diagrams and definitions.`)}</p><a href={`/nctb/2026/class-8/science.pdf#page=${chapter.pages[0]}`} target="_blank" rel="noopener noreferrer">{l("মূল বই খুলুন ↗","Open exact textbook ↗")}</a></div>
 </section><footer>{l("উৎস: তোমার দেওয়া NCTB বিজ্ঞান, অষ্টম শ্রেণি, ২০২৬।","Source: your supplied NCTB Class 8 Science textbook, 2026.")}</footer></div></main>;
}
